# Generated by Django 3.2.8 on 2021-12-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20211129_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='url',
            field=models.URLField(default='https://mooclet.canadacentral.cloudapp.azure.com/engine/api/v1/'),
        ),
    ]
