name: Deploy to Staging

on:
  push:
    branches:
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "iai-app-backend-staging"
          heroku_email: "jordan.han@mail.utoronto.ca"

