# Generated by Django 3.2.8 on 2021-11-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='secondaryEmail',
            new_name='secondary_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dateRegistered',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
